Feature: Display block conent on course page
mudrd8mz/moodle-mod_poster pull request #9
Opened 2020-02-24 22:39 UTC by dasistwas

Hi David,
this is the result of the devcamp of MoodleMoot DACH 2019. Thank you for your great support. I hope you are happy with the new feature and can merge it. 
I am looking forward to your feedback.
Kind regards,
David

2020-03-07 10:40 UTC, mudrd8mz requested changes
Many thanks David for this nice feature. I found it working well. It will be a great addition to the module.

I like the overall design and implementation of the feature. I only left a few notes in the patch which I think could be looked at again.

Additionally, would you like to add some Behat tests covering this feature?

2020-03-07 10:40 UTC, mudrd8mz commented on classes/poster.php
> +// This file is part of mod_datalynx for Moodle - http://moodle.org/
There are a few mentions of datalynx in the patch.

2020-03-07 10:40 UTC, mudrd8mz commented on classes/poster.php
> + *
I usually put something like "Provides the {@link mod_poster\poster} class." here.

2020-03-07 10:40 UTC, mudrd8mz commented on classes/poster.php
> + * @copyright based on the work by 2015 David Mudrak <david@moodle.com>{
Extra trailing curly bracket.

2020-03-07 10:40 UTC, mudrd8mz commented on classes/poster.php
> + * Class poster
This does not add any information, it is a useless comment. The purpose of the class should be described here, e.g. what it represents.

2020-03-07 10:40 UTC, mudrd8mz commented on classes/poster.php
> + * @package mod_datalynx
datalynx

2020-03-07 10:40 UTC, mudrd8mz commented on classes/poster.php
> +     * @var mixed|object|false fetched from get_record.
This should be just `@var object|false` (which I prefer) or `@var mixed` but not both imho

2020-03-07 10:40 UTC, mudrd8mz commented on classes/poster.php
> +     * @return false|mixed|object
Again, I would not mix "mixed" here, it is not a valid type

2020-03-07 10:40 UTC, mudrd8mz commented on classes/poster.php
> +     * @return false|mixed|object
mixed

2020-03-07 10:40 UTC, mudrd8mz commented on db/upgrade.php
> +        // Add new fields to poster table.
The plural is confusing, we add a single field here. Can we have it like "Add a new field 'display' to the poster table."

2020-03-07 10:40 UTC, mudrd8mz commented on lang/en/poster.php
> -
Can we leave the empty line here please

2020-03-07 10:40 UTC, mudrd8mz commented on lib.php
> +        if ($cm->showdescription && strlen(trim($poster->intro))) {
Better to use `html_is_blank()` here, consistently with how the `view_page_description()` method does it

2020-03-07 10:40 UTC, mudrd8mz commented on lib.php
> +    // has_capability('mod/poster:view', $cm->context)) {
Forgotten commented lines?

2020-03-07 10:40 UTC, mudrd8mz commented on lib.php
> +        // $poster->id = (int)$cm->instance;
Forgotten commented lines?

2020-03-07 10:40 UTC, mudrd8mz commented on mod_form.php
> +
I would move the field elsewhere in the form. The original idea was to have the "Display name on view page" right below the "Name" field. I would move this setting to the very bottom of the General section probably.

2020-03-07 10:40 UTC, mudrd8mz commented on renderer.php
> +        $out .= \html_writer::start_div($cssclassmain, array('id' => 'mod_poster-content'));
Why is this change needed? I prefer not to have these backslashes in non-namespaced files personally.

2020-03-07 10:40 UTC, mudrd8mz commented on renderer.php
> +        $out .= \html_writer::start_div('row-fluid');
dtto

2020-03-07 10:40 UTC, mudrd8mz commented on renderer.php
> +        $out .= \html_writer::start_div('row-fluid');
and all the other changes in this file

2020-03-23 08:54 UTC, mudrd8mz commented
Hi @dasistwas - just checking to know if you are considering to work on the suggested fixes yourself, of whether I should do them. I'd still like to have your feature included in the Poster. Thanks for letting me know.

2020-03-23 11:38 UTC, dasistwas commented
Hi @mudrd8mz,
thank you for your reminder. I will try to do that tonight. Current situation: Kids at home and still a lot of tasks to do, so I try to catch up when kids are sleeping.
Kind regards,
David

2020-03-23 19:38 UTC, mudrd8mz commented
No stress at all, it was not meant as a pushing. I just wanted to clarify so that this does not fall off.

2020-03-24 08:02 UTC, dasistwas commented
Hi David,
I resolved all the issues from your code analysis. Thank you for the detailed code review. (I did not see all the comments, because some were hidden, so I just amended the things I forgot to solve). Concerning behat tests: I will put that on my agenda, but I do not think, that this week I will get them done.

2020-03-24 08:40 UTC, mudrd8mz commented
> I did not see all the comments, because some were hidden

What do you mean by that?

2020-03-24 08:50 UTC, dasistwas commented
Github did collapse some comments like that, which I did not see immediatly:
![Screenshot_2020-03-24 Feature Display block conent on course page by dasistwas · Pull Request #9 · mudrd8mz moodle-mod_poster](https://user-images.githubusercontent.com/1620975/77406336-c8e1bf00-6db4-11ea-8a6c-11f7c4f59913.png)

2020-03-24 10:40 UTC, mudrd8mz commented
Ah, ok. Don't worry about Behat.

2020-04-03 20:19 UTC, mudrd8mz commented
Hi @dasistwas 

Thanks for the update. I am playing with the feature and I am experiencing some weird behaviour that I think might easily confuse users.

When the Poster is set to display blocks on the course page, and the editing mode is turned on:
* I noticed that clicking the "move block" widgets lead to PHP notices due to missing regions in the list returned by the theme. I discussed this with Tim Hunt in the chat and it seems that this is a Moodle core bug which could be fixed by https://gist.github.com/mudrd8mz/4771f0a1a18918050575214ae1e06958
* However, when using the new feature with the Classic theme, somehow the Navigation and the Administration blocks were added to the Poster region and I can't get rid of them now. I have no clue why this is happening.
* Additionally, I noticed that the behaviour of some blocks can become a little bit tricky. For example the Comments block display the comments associated with the current page context. So it displays different comments when shown on the course page and when shown on the a separate view.php page. This may be unexpected behaviour for teachers who change the Poster display setting there and back again.

May I ask you to try to reproduce the situation with the Classic theme? I am really worried that this could easily break people's Posters if they use a non-Boost theme...

2021-02-21 11:12 UTC, mudrd8mz commented
I am closing this feature request for now. I am afraid the situation with the behaviour described above (different page context depending on where the blocks are displayed) would be too confusing and hard predictable for end users. Even though I liked the idea very much at the beginning, I now tend to think that the module should better support only blocks on its own view page only.

2021-02-21 11:12 UTC, closed without merging

2021-02-21 16:49 UTC, dasistwas commented
Hi @mudrd8mz,
I do understand your decision. I did not have time to work on that. Some problems you encountered might be solved, others stay tricky:
1) Regions problem: The problem only occurs in editing mode so, the basic idea is to not display the blocks in editing mode, but provide a link to edit the blocks and then you are editing them in the usual way.
2) Classic theme: I will have to check that. But it seems it's a child theme of boost.
3) Context: That might be the most tricky thing. I noticed that as well. So displaying blocks on the course page will have context course and displaying them on the modules page, will have context module. Not sure how to deal with that.

For me the whole block thing would be something to change with Moodle 4.0 UX improvements. Blocks in Moodle have major usability issues, that increased with the implementation of the boost theme and the moodle app.

Hope I can find some time to work on this again. 
Kind regards,
David

2021-02-21 16:53 UTC, mudrd8mz commented
Thanks David @dasistwas 

Re 3., maybe there could be a switch so that the teacher could decide whether they intent to display the blocks on the course page or a special view page. And we would just not support both for consistency.

That might work imho.